// tailwind.config.js
module.exports = {
  mode: 'jit',
  content: [
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary-12': 'hsl(0, 0%, 100%)',
        'primary-12-opacity': 'hsla(0, 0%, 100%, 0.10)',
        'primary-40': 'hsl(0, 0%, 100%)',
        'primary-40-opacity': 'hsla(0, 0%, 100%, 0.40)',
        'primary-100': 'hsl(0, 0%, 0%)',
        base: 'hsl(0, 0%, 3.1%)',
        overlay: 'hsl(0, 0%, 3.1%)',
        'overlay-opacity': 'hsla(0, 0%, 3.1%, 0.50)',
        'copy-primary': 'hsl(0, 0%, 100%)',
        'copy-primary-invert': 'hsl(0, 0%, 3.1%)',
        'copy-secondary': 'hsl(0, 0%, 70.6%)',
        'copy-tertiary': 'hsl(0, 0%, 54.9%)',
        'btn-ring': 'hsl(0, 0%, 54.9%)',
        'btn-primary-label': 'hsl(0, 0%, 3.1%)',
        'btn-primary-label-white': 'hsl(0, 0%, 3.1%)',
        'btn-primary-label-disabled': 'hsl(0, 0%, 70.6%)',
        'btn-primary-base': 'hsl(0, 0%, 100%)',
        'btn-primary-base-invert': 'hsl(0, 0%, 3.1%)',
        'btn-primary-base-hover': 'hsl(0, 0%, 91.4%)',
        'btn-primary-base-disabled': 'hsl(0, 0%, 20%)',
        'btn-primary-white': 'hsl(0, 0%, 100%)',
        'btn-primary-white-hover': 'hsl(0, 0%, 97.6%)',
        'btn-primary-white-disabled': 'hsl(0, 0%, 89%)',
        'btn-secondary-label': 'hsl(0, 0%, 100%)',
        'btn-secondary-label-disabled': 'hsl(0, 0%, 80.4%)',
        'btn-secondary-base': 'hsl(0, 0%, 100%)',
        'btn-secondary-base-opacity': 'hsla(0, 0%, 100%, 0.05)',
        'btn-secondary-base-hover': 'hsl(0, 0%, 100%)',
        'btn-secondary-base-hover-opacity': 'hsla(0, 0%, 100%, 0.10)',
        'btn-link-label': 'hsl(0, 0%, 100%)',
        'btn-link-label-disabled': 'hsl(0, 0%, 38%)',
        'btn-link-underline': 'hsl(0, 0%, 20%)',
        'btn-link-underline-hover': 'hsl(0, 0%, 100%)',
        'btn-link-underline-disabled': 'hsl(0, 0%, 38%)',
        'btn-link-label-focused': 'hsl(0, 0%, 54.9%)',
        'btn-tag-label': 'hsl(0, 0%, 100%)',
        'btn-tag-base': 'hsl(0, 0%, 100%)',
        'btn-tag-base-opacity': 'hsla(0, 0%, 100%, 0.05)',
        'btn-tag-base-hover': 'hsl(0, 0%, 100%)',
        'btn-tag-base-hover-opacity': 'hsla(0, 0%, 100%, 0.10)',
        'btn-nav-label': 'hsl(0, 0%, 3.1%)',
        'btn-nav-label-disabled': 'hsl(0, 0%, 89%)',
        'btn-nav-base': 'hsl(0, 0%, 100%)',
        'btn-nav-base-hover': 'hsl(0, 0%, 89%)',
        'btn-nav-base-disabled': 'hsl(0, 0%, 20%)',
        'btn-media-label': 'hsl(0, 0%, 100%)',
        'btn-media-base': 'hsl(0, 0%, 3.1%)',
        'btn-media-base-hover': 'hsl(0, 0%, 20%)',
        'nav-label': 'hsl(0, 0%, 100%)',
        'nav-label-inactive': 'hsl(0, 0%, 38%)',
        'nav-label-hover': 'hsl(0, 0%, 100%)',
        'nav-base': 'hsl(0, 0%, 89%)',
        'nav-base-opacity': 'hsla(0, 0%, 89%, 0.20)',
        'nav-line': 'hsl(0, 0%, 9%)',
        'surface-primary': 'hsl(0, 0%, 9%)',
        'surface-primary-invert': 'hsl(0, 0%, 97.6%)',
        'surface-secondary': 'hsl(0, 0%, 100%)',
        'surface-secondary-opacity': 'hsla(0, 0%, 100%, 0.05)',
        'surface-loading': 'hsl(0, 0%, 20%)',
        'surface-card': 'hsl(0, 0%, 9%)',
        'surface-card-transparent': 'hsl(0, 0%, 9%)',
        'surface-card-transparent-opacity': 'hsla(0, 0%, 9%, 0)',
        'syntax-copy': 'hsl(0, 0%, 100%)',
        'syntax-comment': 'hsl(0, 0%, 70.6%)',
        'syntax-highlight': 'hsl(0, 0%, 100%)',
        'syntax-highlight-opacity': 'hsla(0, 0%, 100%, 0.05)',
        'syntax-error': 'hsl(350.7, 89.4%, 48%)',
        'syntax-operator': 'hsl(17.7, 90.8%, 42.5%)',
        'syntax-variable': 'hsl(47.2, 63.5%, 33.3%)',
        'syntax-string': 'hsl(150.2, 96.9%, 25.3%)',
        'syntax-data': 'hsl(195.7, 55.2%, 39.4%)',
        'syntax-keyword': 'hsl(219.8, 76.4%, 55.1%)',
        'syntax-function': 'hsl(255.5, 95.5%, 65.1%)',
        'syntax-const': 'hsl(320.6, 88.1%, 46.1%)',
        'footer-base': 'hsl(0, 0%, 89%)',
        'footer-base-opacity': 'hsla(0, 0%, 89%, 0.31)',
        'footer-link': 'hsl(0, 0%, 100%)',
        'footer-label': 'hsl(0, 0%, 70.6%)',
        'footer-label-inactive': 'hsl(0, 0%, 54.9%)',
        'input-label': 'hsl(0, 0%, 100%)',
        'input-label-error': 'hsl(350.7, 89.4%, 48%)',
        'input-base': 'hsl(0, 0%, 3.1%)',
        'input-base-suffix': 'hsl(0, 0%, 3.1%)',
        'input-base-disabled': 'hsl(0, 0%, 3.1%)',
        'input-border': 'hsl(0, 0%, 30.6%)',
        'input-border-hover': 'hsl(0, 0%, 54.9%)',
        'input-border-focus': 'hsl(0, 0%, 89%)',
        'input-border-disabled': 'hsl(0, 0%, 30.6%)',
        'input-border-filled': 'hsl(0, 0%, 38%)',
        'input-border-error': 'hsl(350.7, 89.4%, 48%)',
        'radio-base': 'hsl(0, 0%, 38%)',
        'radio-base-hover': 'hsl(0, 0%, 54.9%)',
        'radio-base-disabled': 'hsl(0, 0%, 54.9%)',
        'radio-base-selected': 'hsl(0, 0%, 97.6%)',
        'radio-base-error': 'hsl(350.7, 89.4%, 48%)',
        'radio-border': 'hsl(0, 0%, 70.6%)',
        'radio-border-hover': 'hsl(0, 0%, 38%)',
        'dropdown-label': 'hsl(0, 0%, 100%)',
        'dropdown-label-disabled': 'hsl(0, 0%, 38%)',
        'dropdown-label-error': 'hsl(350.7, 89.4%, 48%)',
        'dropdown-base': 'hsl(0, 0%, 3.1%)',
        'dropdown-base-disabled': 'hsl(0, 0%, 20%)',
        'dropdown-base-hover': 'hsl(0, 0%, 9%)',
        'dropdown-border': 'hsl(0, 0%, 30.6%)',
        'dropdown-border-hover': 'hsl(0, 0%, 54.9%)',
        'dropdown-border-focus': 'hsl(0, 0%, 89%)',
        'dropdown-border-disabled': 'hsl(0, 0%, 30.6%)',
        'dropdown-border-error': 'hsl(350.7, 89.4%, 48%)',
        'stroke-primary': 'hsl(0, 0%, 20%)',
        'stroke-secondary': 'hsl(0, 0%, 54.9%)',
        'stroke-tertiary': 'hsl(0, 0%, 100%)',
      },
    },
  },
  plugins: [
    function({ addBase }) {
      addBase({
        ':root': {
          '--twc-primary-12': '0, 0%, 100%',
          '--twc-primary-12-opacity': '0.10',
          '--twc-primary-40': '0, 0%, 100%',
          '--twc-primary-40-opacity': '0.40',
          '--twc-primary-100': '0, 0%, 0%',
          '--twc-base': '0 0% 3.1%',
          '--twc-overlay': '0, 0%, 3.1%',
          '--twc-overlay-opacity': '0.50',
          '--twc-copy-primary': '0, 0%, 100%',
          '--twc-copy-primary--invert': '0, 0%, 3.1%',
          '--twc-copy-secondary': '0, 0%, 70.6%',
          '--twc-copy-tertiary': '0, 0%, 54.9%',
          '--twc-btn-ring': '0, 0%, 54.9%',
          '--twc-btn-primary-label': '0, 0%, 3.1%',
          '--twc-btn-primary-label-white': '0, 0%, 3.1%',
          '--twc-btn-primary-label--disabled': '0, 0%, 70.6%',
          '--twc-btn-primary-base': '0, 0%, 100%',
          '--twc-btn-primary-base--invert': '0, 0%, 3.1%',
          '--twc-btn-primary-base--hover': '0, 0%, 91.4%',
          '--twc-btn-primary-base--disabled': '0, 0%, 20%',
          '--twc-btn-primary-white': '0, 0%, 100%',
          '--twc-btn-primary-white--hover': '0, 0%, 97.6%',
          '--twc-btn-primary-white--disabled': '0, 0%, 89%',
          '--twc-btn-secondary-label': '0, 0%, 100%',
          '--twc-btn-secondary-label--disabled': '0, 0%, 80.4%',
          '--twc-btn-secondary-base': '0, 0%, 100%',
          '--twc-btn-secondary-base-opacity': '0.05',
          '--twc-btn-secondary-base--hover': '0, 0%, 100%',
          '--twc-btn-secondary-base--hover-opacity': '0.10',
          '--twc-btn-link-label': '0, 0%, 100%',
          '--twc-btn-link-label--disabled': '0, 0%, 38%',
          '--twc-btn-link-underline': '0, 0%, 20%',
          '--twc-btn-link-underline--hover': '0, 0%, 100%',
          '--twc-btn-link-underline--disabled': '0, 0%, 38%',
          '--twc-btn-link-label--focused': '0, 0%, 54.9%',
          '--twc-btn-tag-label': '0, 0%, 100%',
          '--twc-btn-tag-base': '0, 0%, 100%',
          '--twc-btn-tag-base-opacity': '0.05',
          '--twc-btn-tag-base--hover': '0, 0%, 100%',
          '--twc-btn-tag-base--hover-opacity': '0.10',
          '--twc-btn-nav-label': '0, 0%, 3.1%',
          '--twc-btn-nav-label--disabled': '0, 0%, 89%',
          '--twc-btn-nav-base': '0, 0%, 100%',
          '--twc-btn-nav-base--hover': '0, 0%, 89%',
          '--twc-btn-nav-base--disabled': '0, 0%, 20%',
          '--twc-btn-media-label': '0, 0%, 100%',
          '--twc-btn-media-base': '0, 0%, 3.1%',
          '--twc-btn-media-base--hover': '0, 0%, 20%',
          '--twc-nav-label': '0, 0%, 100%',
          '--twc-nav-label--inactive': '0, 0%, 38%',
          '--twc-nav-label--hover': '0, 0%, 100%',
          '--twc-nav-base': '0, 0%, 89%',
          '--twc-nav-base-opacity': '0.20',
          '--twc-nav-line': '0, 0%, 9%',
          '--twc-surface-primary': '0, 0%, 9%',
          '--twc-surface-primary--invert': '0, 0%, 97.6%',
          '--twc-surface-secondary': '0, 0%, 100%',
          '--twc-surface-secondary-opacity': '0.05',
          '--twc-surface-loading': '0, 0%, 20%',
          '--twc-surface-card': '0, 0%, 9%',
          '--twc-surface-card--transparent': '0, 0%, 9%',
          '--twc-surface-card--transparent-opacity': '0.00',
          '--twc-syntax-copy': '0, 0%, 100%',
          '--twc-syntax-comment': '0, 0%, 70.6%',
          '--twc-syntax-highlight': '0, 0%, 100%',
          '--twc-syntax-highlight-opacity': '0.05',
          '--twc-syntax-error': '350.7, 89.4%, 48%',
          '--twc-syntax-operator': '17.7, 90.8%, 42.5%',
          '--twc-syntax-variable': '47.2, 63.5%, 33.3%',
          '--twc-syntax-string': '150.2, 96.9%, 25.3%',
          '--twc-syntax-data': '195.7, 55.2%, 39.4%',
          '--twc-syntax-keyword': '219.8, 76.4%, 55.1%',
          '--twc-syntax-function': '255.5, 95.5%, 65.1%',
          '--twc-syntax-const': '320.6, 88.1%, 46.1%',
          '--twc-footer-base': '0, 0%, 89%',
          '--twc-footer-base-opacity': '0.31',
          '--twc-footer-link': '0, 0%, 100%',
          '--twc-footer-label': '0, 0%, 70.6%',
          '--twc-footer-label--inactive': '0, 0%, 54.9%',
          '--twc-input-label': '0, 0%, 100%',
          '--twc-input-label--error': '350.7, 89.4%, 48%',
          '--twc-input-base': '0, 0%, 3.1%',
          '--twc-input-base--suffix': '0, 0%, 3.1%',
          '--twc-input-base--disabled': '0, 0%, 3.1%',
          '--twc-input-border': '0, 0%, 30.6%',
          '--twc-input-border--hover': '0, 0%, 54.9%',
          '--twc-input-border--focus': '0, 0%, 89%',
          '--twc-input-border--disabled': '0, 0%, 30.6%',
          '--twc-input-border--filled': '0, 0%, 38%',
          '--twc-input-border--error': '350.7, 89.4%, 48%',
          '--twc-radio-base': '0, 0%, 38%',
          '--twc-radio-base--hover': '0, 0%, 54.9%',
          '--twc-radio-base--disabled': '0, 0%, 54.9%',
          '--twc-radio-base--selected': '0, 0%, 97.6%',
          '--twc-radio-base--error': '350.7, 89.4%, 48%',
          '--twc-radio-border': '0, 0%, 70.6%',
          '--twc-radio-border--hover': '0, 0%, 38%',
          '--twc-dropdown-label': '0, 0%, 100%',
          '--twc-dropdown-label--disabled': '0, 0%, 38%',
          '--twc-dropdown-label--error': '350.7, 89.4%, 48%',
          '--twc-dropdown-base': '0, 0%, 3.1%',
          '--twc-dropdown-base--disabled': '0, 0%, 20%',
          '--twc-dropdown-base--hover': '0, 0%, 9%',
          '--twc-dropdown-border': '0, 0%, 30.6%',
          '--twc-dropdown-border--hover': '0, 0%, 54.9%',
          '--twc-dropdown-border--focus': '0, 0%, 89%',
          '--twc-dropdown-border--disabled': '0, 0%, 30.6%',
          '--twc-dropdown-border--error': '350.7, 89.4%, 48%',
          '--twc-stroke-primary': '0, 0%, 20%',
          '--twc-stroke-secondary': '0, 0%, 54.9%',
          '--twc-stroke-tertiary': '0, 0%, 100%',
        },
      });
    },
  ],
};
